export const CITY_ADD = 'CITY_ADD';
export const CITY_DELETE = 'CITY_DELETE';
export const CITY_SET_FILTER = 'CITY_SET_FILTER';


export const WEATHER_CLEAR = 'WEATHER_CLEAR';
export const WEATHER_HAS_ERRORED = 'WEATHER_HAS_ERRORED';
export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING';
export const WEATHER_FETCH_DATA_SUCCESS = 'WEATHER_FETCH_DATA_SUCCESS';